# Generated by Django 5.1.1 on 2024-10-13 21:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='MenuTable',
            new_name='Menu',
        ),
    ]
